/* ====================================================
   ClearJob — Mock Data Layer
   Separated by entity type; mirrors production schema
   ==================================================== */

// ---- Employers ----
const EMPLOYERS = [
  {
    id: 'emp1',
    name: 'טכנולוגיות אמזיג',
    industry: 'תוכנה וטכנולוגיה',
    size: '200–500',
    logo: null,
    isConfidential: false,
    employerType: 'direct',
    responseTime: 3,
    responseRate: 94,
    tags: ['מגיב מהר', 'שכר גלוי', 'תהליך קצר']
  },
  {
    id: 'emp2',
    name: 'קבוצת ריאלטק',
    industry: 'פיננסים ובנקאות',
    size: '1,000–5,000',
    logo: null,
    isConfidential: false,
    employerType: 'direct',
    responseTime: 5,
    responseRate: 88,
    tags: ['שכר גלוי', 'מעסיק שקוף']
  },
  {
    id: 'emp3',
    name: null,
    industry: 'מסעדנות ואירוח',
    size: '200–500',
    logo: null,
    isConfidential: true,
    confidentialityLevel: 'partial',
    employerType: 'direct',
    area: 'מרכז',
    revealCondition: 'לאחר סינון ראשוני',
    responseTime: 4,
    responseRate: 80,
    tags: ['מתאים לדיסקרטיים']
  },
  {
    id: 'emp4',
    name: null,
    industry: 'שירותי בריאות',
    size: '50–200',
    logo: null,
    isConfidential: true,
    confidentialityLevel: 'full',
    employerType: 'direct',
    area: 'צפון',
    revealCondition: 'רק לאחר אישור ידני',
    responseTime: 7,
    responseRate: 72,
    tags: []
  },
  {
    id: 'emp5',
    name: 'דרך הקריירה',
    industry: 'השמה וגיוס',
    size: '10–50',
    logo: null,
    isConfidential: false,
    employerType: 'agency',
    responseTime: 2,
    responseRate: 97,
    tags: ['מגיב מהר', 'שכר גלוי', 'תהליך קצר', 'נותן תשובה לכל מועמד']
  }
];

// ---- Jobs ----
const JOBS = [
  {
    id: 'job1',
    title: 'מנהל/ת רכש',
    employerId: 'emp3',
    category: 'רכש ולוגיסטיקה',
    location: 'תל אביב',
    workModel: 'hybrid',
    workDaysOffice: 4,
    employmentType: 'fullTime',
    experienceLevel: 'mid',
    description: 'אנו מחפשים מנהל/ת רכש מנוסה להוביל את תחום הרכש האסטרטגי בארגון המזון והאירוח שלנו. התפקיד כולל ניהול ספקים, מו"מ, ועבודה מול צוותי תפעול.',
    responsibilities: ['ניהול קשרי ספקים אסטרטגיים', 'ניהול מו"מ וחוזים', 'בניית תהליכי רכש יעילים', 'ניתוח עלויות ויעדי חיסכון', 'עבודה מול מחלקות תפעול ופיננסים'],
    mustHaveRequirements: ['ניסיון של 3+ שנים ברכש', 'שליטה ב-Priority ERP', 'ניסיון בניהול ספקים'],
    niceToHaveRequirements: ['ניסיון בענף המזון', 'הסמכה בניהול שרשרת אספקה'],
    salaryMin: 18000,
    salaryMax: 22000,
    salaryType: 'monthly',
    salaryFlexible: true,
    includesBonus: true,
    bonusPercent: 10,
    includesCar: false,
    includesStudyFund: true,
    includesMeals: true,
    includesOptions: false,
    salaryNotes: 'גמישות קיימת למועמד/ת חזק/ה',
    createdAt: '2026-05-28',
    updatedAt: '2026-05-30',
    lastBoostedAt: '2026-05-30',
    applicantCount: 74,
    viewedApplicantCount: 31,
    interviewCount: 6,
    rejectedCount: 18,
    pendingCount: 43,
    reviewMethod: { humanReview: true, atsReview: true, aiAssisted: false, screeningQuestions: true },
    hiringProcess: [
      { id: 's1', title: 'שיחת HR', description: 'שיחת מיון ראשונית', estimatedMinutes: 20, interviewerRole: 'מגייס/ת' },
      { id: 's2', title: 'ראיון מנהל ישיר', description: 'ראיון מקצועי מעמיק', estimatedMinutes: 45, interviewerRole: 'מנהל/ת רכש' },
      { id: 's3', title: 'ראיון סמנכ"ל', description: 'ראיון סגירה', estimatedMinutes: 30, interviewerRole: 'סמנכ"ל תפעול' }
    ],
    hasHomeAssignment: false,
    averageResponseDays: 4,
    averageProcessDays: 21,
    status: 'active',
    transparencyScore: 92
  },
  {
    id: 'job2',
    title: 'מנהל/ת מוצר',
    employerId: 'emp1',
    category: 'מוצר ועיצוב',
    location: 'תל אביב',
    workModel: 'hybrid',
    workDaysOffice: 3,
    employmentType: 'fullTime',
    experienceLevel: 'senior',
    description: 'הזדמנות להוביל אסטרטגיית מוצר ב-SaaS הצומח שלנו. נחפש מנהל/ת מוצר בעל/ת חזון, ניסיון ב-B2B וחשיבה נתונים-מובילה.',
    responsibilities: ['גיבוש רודמאפ מוצר', 'עבודה עם הנדסה ועיצוב', 'ניתוח נתוני שימוש', 'הגדרת מדדי הצלחה', 'ניהול בעלי עניין'],
    mustHaveRequirements: ['5+ שנות ניסיון בניהול מוצר', 'ניסיון ב-SaaS B2B', 'שליטה ב-SQL בסיסי'],
    niceToHaveRequirements: ['ניסיון בחברת סטארטאפ', 'הכרות עם Figma'],
    salaryMin: 28000,
    salaryMax: 38000,
    salaryType: 'monthly',
    salaryFlexible: true,
    includesBonus: true,
    bonusPercent: 15,
    includesCar: false,
    includesStudyFund: true,
    includesMeals: true,
    includesOptions: true,
    salaryNotes: 'כולל אופציות',
    createdAt: '2026-05-20',
    updatedAt: '2026-05-29',
    lastBoostedAt: null,
    applicantCount: 143,
    viewedApplicantCount: 87,
    interviewCount: 12,
    rejectedCount: 55,
    pendingCount: 56,
    reviewMethod: { humanReview: true, atsReview: false, aiAssisted: true, screeningQuestions: false },
    hiringProcess: [
      { id: 's1', title: 'שיחת מיון', description: 'שיחה קצרה עם HR', estimatedMinutes: 20, interviewerRole: 'HR' },
      { id: 's2', title: 'מבחן מוצר', description: 'case study', estimatedMinutes: 90, interviewerRole: 'עצמאי' },
      { id: 's3', title: 'ראיון מקצועי', description: 'ראיון עם מנהל מוצר ראשי', estimatedMinutes: 60, interviewerRole: 'Head of Product' },
      { id: 's4', title: 'ראיון C-Level', description: 'שיחה עם CPO', estimatedMinutes: 30, interviewerRole: 'CPO' }
    ],
    hasHomeAssignment: true,
    homeAssignmentEstimatedHours: 3,
    homeAssignmentPaid: false,
    averageResponseDays: 3,
    averageProcessDays: 28,
    status: 'active',
    transparencyScore: 88
  },
  {
    id: 'job3',
    title: 'נציג/ת שירות לקוחות',
    employerId: 'emp2',
    category: 'שירות לקוחות',
    location: 'רמת גן',
    workModel: 'hybrid',
    workDaysOffice: 4,
    employmentType: 'fullTime',
    experienceLevel: 'junior',
    description: 'מחפשים נציג/ת שירות לקוחות לצוות שלנו. העבודה כוללת מענה ללקוחות בטלפון, אימייל וצ\'אט, פתרון תקלות ומתן שירות ברמה גבוהה.',
    responsibilities: ['מענה לפניות לקוחות', 'פתרון בעיות', 'עבודה עם מערכות CRM', 'תיעוד פניות'],
    mustHaveRequirements: ['ניסיון שנתיים+ בשירות לקוחות', 'שפה ערבית — יתרון'],
    niceToHaveRequirements: ['ניסיון עם Salesforce', 'ניסיון בשירות דיגיטלי'],
    salaryMin: 9000,
    salaryMax: 12000,
    salaryType: 'monthly',
    salaryFlexible: false,
    includesBonus: false,
    includesCar: false,
    includesStudyFund: false,
    includesMeals: true,
    includesOptions: false,
    createdAt: '2026-05-25',
    updatedAt: '2026-05-30',
    lastBoostedAt: '2026-05-28',
    applicantCount: 210,
    viewedApplicantCount: 45,
    interviewCount: 8,
    rejectedCount: 37,
    pendingCount: 165,
    reviewMethod: { humanReview: false, atsReview: true, aiAssisted: false, screeningQuestions: true },
    hiringProcess: [
      { id: 's1', title: 'שאלון סינון', description: 'שאלון אונליין', estimatedMinutes: 10, interviewerRole: 'מערכת' },
      { id: 's2', title: 'ראיון HR', description: 'ראיון טלפוני', estimatedMinutes: 25, interviewerRole: 'HR' },
      { id: 's3', title: 'ראיון מנהל', description: 'ראיון עם ראש צוות', estimatedMinutes: 30, interviewerRole: 'ראש צוות' }
    ],
    hasHomeAssignment: false,
    averageResponseDays: 7,
    averageProcessDays: 14,
    status: 'active',
    transparencyScore: 75
  },
  {
    id: 'job4',
    title: 'חשב/ת שכר',
    employerId: 'emp4',
    category: 'כספים וחשבונאות',
    location: 'חיפה',
    workModel: 'office',
    workDaysOffice: 5,
    employmentType: 'fullTime',
    experienceLevel: 'mid',
    description: 'תפקיד חשב/ת שכר בארגון בתחום שירותי הבריאות. התפקיד כולל ניהול מלא של תהליכי שכר לכ-300 עובדים.',
    responsibilities: ['עיבוד שכר חודשי', 'ניהול הפרשות סוציאליות', 'דיווחים לרשויות', 'ייעוץ לעובדים'],
    mustHaveRequirements: ['3+ שנות ניסיון בחשבות שכר', 'שליטה בתוכנת שכר מוכרת', 'הכרת חוקי עבודה'],
    niceToHaveRequirements: ['ניסיון בענף הבריאות'],
    salaryMin: 14000,
    salaryMax: 18000,
    salaryType: 'monthly',
    salaryFlexible: true,
    includesBonus: false,
    includesCar: false,
    includesStudyFund: true,
    includesMeals: false,
    includesOptions: false,
    createdAt: '2026-05-15',
    updatedAt: '2026-05-26',
    lastBoostedAt: null,
    applicantCount: 38,
    viewedApplicantCount: 20,
    interviewCount: 4,
    rejectedCount: 14,
    pendingCount: 18,
    reviewMethod: { humanReview: true, atsReview: false, aiAssisted: false, screeningQuestions: false },
    hiringProcess: [
      { id: 's1', title: 'ראיון HR', description: 'ראיון ראשוני', estimatedMinutes: 30, interviewerRole: 'HR' },
      { id: 's2', title: 'ראיון מקצועי', description: 'ראיון עם מנהל/ת כספים', estimatedMinutes: 45, interviewerRole: 'CFO' }
    ],
    hasHomeAssignment: false,
    averageResponseDays: 6,
    averageProcessDays: 18,
    status: 'active',
    transparencyScore: 85
  },
  {
    id: 'job5',
    title: 'מנהל/ת סושיאל מדיה',
    employerId: 'emp1',
    category: 'שיווק ותקשורת',
    location: 'תל אביב',
    workModel: 'remote',
    workDaysOffice: 0,
    employmentType: 'fullTime',
    experienceLevel: 'mid',
    description: 'מחפשים מנהל/ת סושיאל מדיה יצירתי/ת עם חוש נראטיבי חזק. התפקיד כולל ניהול כל הפלטפורמות, ייצור תוכן ואסטרטגיה דיגיטלית.',
    responsibilities: ['ניהול פלטפורמות סושיאל', 'ייצור תוכן ויזואלי', 'ניהול קהילה', 'ניתוח ביצועים', 'שיתוף פעולה עם שיווק'],
    mustHaveRequirements: ['2+ שנות ניסיון בסושיאל', 'ידע בCanva/Adobe', 'הכרת מטריקות'],
    niceToHaveRequirements: ['ניסיון בניהול קמפיינים ממומנים', 'ניסיון עם כלי AI'],
    salaryMin: 13000,
    salaryMax: 17000,
    salaryType: 'monthly',
    salaryFlexible: true,
    includesBonus: false,
    includesCar: false,
    includesStudyFund: true,
    includesMeals: true,
    includesOptions: true,
    createdAt: '2026-05-22',
    updatedAt: '2026-05-31',
    lastBoostedAt: '2026-05-31',
    applicantCount: 89,
    viewedApplicantCount: 42,
    interviewCount: 7,
    rejectedCount: 28,
    pendingCount: 47,
    reviewMethod: { humanReview: true, atsReview: false, aiAssisted: true, screeningQuestions: true },
    hiringProcess: [
      { id: 's1', title: 'שיחת מיון', description: 'שיחה קצרה עם HR', estimatedMinutes: 20, interviewerRole: 'HR' },
      { id: 's2', title: 'מבחן יצירתיות', description: 'מטלת בית קצרה', estimatedMinutes: 120, interviewerRole: 'עצמאי' },
      { id: 's3', title: 'ראיון מקצועי', description: 'ראיון עם מנהל שיווק', estimatedMinutes: 45, interviewerRole: 'VP Marketing' }
    ],
    hasHomeAssignment: true,
    homeAssignmentEstimatedHours: 2,
    homeAssignmentPaid: false,
    averageResponseDays: 3,
    averageProcessDays: 17,
    status: 'active',
    transparencyScore: 90
  },
  {
    id: 'job6',
    title: 'מפתח/ת Full Stack',
    employerId: 'emp1',
    category: 'פיתוח תוכנה',
    location: 'תל אביב',
    workModel: 'hybrid',
    workDaysOffice: 2,
    employmentType: 'fullTime',
    experienceLevel: 'mid',
    description: 'נחפש מפתח/ת Full Stack להצטרף לצוות הפיתוח שלנו. עבודה עם React, Node.js, PostgreSQL ו-AWS. סביבת עבודה גמישה ומשפחתית.',
    responsibilities: ['פיתוח פיצ\'רים חדשים', 'קוד review', 'עבודה עם ה-Product', 'שמירת איכות קוד'],
    mustHaveRequirements: ['3+ שנות ניסיון ב-React', '3+ שנות ניסיון ב-Node.js', 'שליטה ב-SQL'],
    niceToHaveRequirements: ['ניסיון עם AWS', 'ניסיון עם TypeScript'],
    salaryMin: 25000,
    salaryMax: 35000,
    salaryType: 'monthly',
    salaryFlexible: true,
    includesBonus: true,
    bonusPercent: 10,
    includesCar: false,
    includesStudyFund: true,
    includesMeals: true,
    includesOptions: true,
    createdAt: '2026-05-18',
    updatedAt: '2026-05-30',
    lastBoostedAt: '2026-05-29',
    applicantCount: 178,
    viewedApplicantCount: 102,
    interviewCount: 15,
    rejectedCount: 67,
    pendingCount: 76,
    reviewMethod: { humanReview: true, atsReview: false, aiAssisted: true, screeningQuestions: false },
    hiringProcess: [
      { id: 's1', title: 'שיחת HR', description: 'שיחה קצרה', estimatedMinutes: 20, interviewerRole: 'HR' },
      { id: 's2', title: 'ריאיון טכני ראשוני', description: 'שאלות טכניות', estimatedMinutes: 60, interviewerRole: 'Senior Dev' },
      { id: 's3', title: 'Home Assignment', description: 'מטלה מעשית', estimatedMinutes: 180, interviewerRole: 'עצמאי' },
      { id: 's4', title: 'ראיון סיום', description: 'ראיון עם CTO', estimatedMinutes: 45, interviewerRole: 'CTO' }
    ],
    hasHomeAssignment: true,
    homeAssignmentEstimatedHours: 3,
    homeAssignmentPaid: false,
    averageResponseDays: 3,
    averageProcessDays: 35,
    status: 'active',
    transparencyScore: 87
  },
  {
    id: 'job7',
    title: 'מנהל/ת תפעול',
    employerId: 'emp3',
    category: 'תפעול וניהול',
    location: 'תל אביב',
    workModel: 'office',
    workDaysOffice: 5,
    employmentType: 'fullTime',
    experienceLevel: 'senior',
    description: 'תפקיד מנהל/ת תפעול לרשת קמעונאית גדולה. ניהול כלל התפעול, ספקים, לוגיסטיקה וצוותים מבצעיים.',
    responsibilities: ['ניהול תפעול יומיומי', 'אחריות על ספקים', 'ניהול תקציב תפעולי', 'הובלת שיפור תהליכים', 'ניהול צוות של 15 איש'],
    mustHaveRequirements: ['5+ שנות ניסיון בתפעול', 'ניסיון בניהול צוות', 'ניסיון ברשת קמעונאית'],
    niceToHaveRequirements: ['MBA', 'ניסיון בבניית נהלים'],
    salaryMin: 22000,
    salaryMax: 30000,
    salaryType: 'monthly',
    salaryFlexible: false,
    includesBonus: true,
    bonusPercent: 12,
    includesCar: true,
    includesStudyFund: true,
    includesMeals: true,
    includesOptions: false,
    createdAt: '2026-05-10',
    updatedAt: '2026-05-28',
    lastBoostedAt: null,
    applicantCount: 54,
    viewedApplicantCount: 28,
    interviewCount: 5,
    rejectedCount: 19,
    pendingCount: 26,
    reviewMethod: { humanReview: true, atsReview: true, aiAssisted: false, screeningQuestions: true },
    hiringProcess: [
      { id: 's1', title: 'שאלון מקדים', description: 'שאלות ניסיון', estimatedMinutes: 15, interviewerRole: 'מערכת' },
      { id: 's2', title: 'ראיון HR', description: 'ראיון ראשוני', estimatedMinutes: 30, interviewerRole: 'HR' },
      { id: 's3', title: 'ראיון מקצועי', description: 'ראיון מנכ"ל', estimatedMinutes: 60, interviewerRole: 'מנכ"ל' }
    ],
    hasHomeAssignment: false,
    averageResponseDays: 5,
    averageProcessDays: 25,
    status: 'active',
    transparencyScore: 83
  },
  {
    id: 'job8',
    title: 'אנליסט/ית נתונים',
    employerId: 'emp2',
    category: 'נתונים ו-BI',
    location: 'רמת גן',
    workModel: 'hybrid',
    workDaysOffice: 3,
    employmentType: 'fullTime',
    experienceLevel: 'mid',
    description: 'נחפש אנליסט/ית נתונים לצוות ה-Data שלנו בחברת הפיננסים. עבודה עם דאטה גדולה, בניית דשבורדים ותמיכה בקבלת החלטות.',
    responsibilities: ['ניתוח דאטה עסקי', 'בניית דשבורדים', 'SQL ו-Python', 'דוחות הנהלה', 'פיתוח מדדים עסקיים'],
    mustHaveRequirements: ['2+ שנות ניסיון בניתוח נתונים', 'שליטה ב-SQL', 'ידע ב-Python/R'],
    niceToHaveRequirements: ['ניסיון עם Power BI / Tableau', 'ניסיון בפיננסים'],
    salaryMin: 20000,
    salaryMax: 27000,
    salaryType: 'monthly',
    salaryFlexible: true,
    includesBonus: true,
    bonusPercent: 8,
    includesCar: false,
    includesStudyFund: true,
    includesMeals: true,
    includesOptions: false,
    createdAt: '2026-05-24',
    updatedAt: '2026-05-31',
    lastBoostedAt: '2026-05-31',
    applicantCount: 97,
    viewedApplicantCount: 55,
    interviewCount: 9,
    rejectedCount: 32,
    pendingCount: 52,
    reviewMethod: { humanReview: true, atsReview: true, aiAssisted: false, screeningQuestions: true },
    hiringProcess: [
      { id: 's1', title: 'שיחת HR', description: 'שיחה ראשונית', estimatedMinutes: 20, interviewerRole: 'HR' },
      { id: 's2', title: 'בחינת SQL', description: 'מבחן SQL מקוון', estimatedMinutes: 60, interviewerRole: 'מערכת' },
      { id: 's3', title: 'ראיון מקצועי', description: 'ראיון עם ראש צוות Data', estimatedMinutes: 60, interviewerRole: 'Data Lead' }
    ],
    hasHomeAssignment: false,
    averageResponseDays: 5,
    averageProcessDays: 21,
    status: 'active',
    transparencyScore: 91
  },
  {
    id: 'job9',
    title: 'מנהל/ת מכירות',
    employerId: 'emp5',
    category: 'מכירות',
    location: 'ירושלים',
    workModel: 'hybrid',
    workDaysOffice: 3,
    employmentType: 'fullTime',
    experienceLevel: 'senior',
    description: 'פוזיציה בחברה תעשייתית מובילה (מופעלת דרך חברת השמה). מנהל/ת מכירות לאחריות על אזור הדרום.',
    responsibilities: ['ניהול תיק לקוחות', 'פיתוח עסקי', 'ניהול מכרזים', 'ניהול צוות מכירות קטן'],
    mustHaveRequirements: ['5+ שנות ניסיון במכירות B2B', 'ניסיון בתעשייה', 'רישיון נהיגה'],
    niceToHaveRequirements: ['ניסיון בניהול צוות', 'ניסיון עם Salesforce'],
    salaryMin: 20000,
    salaryMax: 26000,
    salaryType: 'basePlusCommission',
    salaryFlexible: true,
    includesBonus: true,
    bonusPercent: 0,
    includesCar: true,
    includesStudyFund: true,
    includesMeals: false,
    includesOptions: false,
    salaryNotes: 'בסיס + עמלות. OTE שנתי: 360,000–420,000 ₪',
    createdAt: '2026-05-27',
    updatedAt: '2026-05-31',
    lastBoostedAt: null,
    applicantCount: 41,
    viewedApplicantCount: 29,
    interviewCount: 5,
    rejectedCount: 12,
    pendingCount: 24,
    reviewMethod: { humanReview: true, atsReview: false, aiAssisted: false, screeningQuestions: false },
    hiringProcess: [
      { id: 's1', title: 'שיחה עם משרד ההשמה', description: 'שיחת מיון ראשונית', estimatedMinutes: 30, interviewerRole: 'מגייס/ת השמה' },
      { id: 's2', title: 'ראיון אצל המעסיק', description: 'ראיון עם מנהל מכירות', estimatedMinutes: 60, interviewerRole: 'VP Sales' },
      { id: 's3', title: 'ראיון מנכ"ל', description: 'ראיון סיום', estimatedMinutes: 30, interviewerRole: 'מנכ"ל' }
    ],
    hasHomeAssignment: false,
    averageResponseDays: 2,
    averageProcessDays: 14,
    status: 'active',
    transparencyScore: 89
  },
  {
    id: 'job10',
    title: 'רכז/ת גיוס',
    employerId: 'emp5',
    category: 'משאבי אנוש',
    location: 'תל אביב',
    workModel: 'hybrid',
    workDaysOffice: 3,
    employmentType: 'fullTime',
    experienceLevel: 'junior',
    description: 'רוצה לעבוד בתחום הגיוס? הצטרף/י לצוות שלנו בחברת ההשמה. עבודה עם מועמדים ומעסיקים, ניהול תהליכי גיוס מקצה לקצה.',
    responsibilities: ['מיון קורות חיים', 'שיחות מיון', 'תיאום ראיונות', 'ניהול מועמדויות', 'עבודה מול לקוחות'],
    mustHaveRequirements: ['1+ שנות ניסיון בגיוס', 'תקשורת מעולה'],
    niceToHaveRequirements: ['ניסיון עם ATS'],
    salaryMin: 9000,
    salaryMax: 13000,
    salaryType: 'monthly',
    salaryFlexible: true,
    includesBonus: true,
    bonusPercent: 0,
    includesCar: false,
    includesStudyFund: false,
    includesMeals: true,
    includesOptions: false,
    salaryNotes: 'בסיס + עמלות על גיוסים',
    createdAt: '2026-05-29',
    updatedAt: '2026-05-31',
    lastBoostedAt: '2026-05-31',
    applicantCount: 34,
    viewedApplicantCount: 22,
    interviewCount: 5,
    rejectedCount: 9,
    pendingCount: 20,
    reviewMethod: { humanReview: true, atsReview: false, aiAssisted: false, screeningQuestions: true },
    hiringProcess: [
      { id: 's1', title: 'שיחת מיון', description: '15 דקות', estimatedMinutes: 15, interviewerRole: 'שותף/ה' },
      { id: 's2', title: 'ראיון', description: 'ראיון מקצועי', estimatedMinutes: 45, interviewerRole: 'מנהל/ת גיוס' }
    ],
    hasHomeAssignment: false,
    averageResponseDays: 2,
    averageProcessDays: 10,
    status: 'active',
    transparencyScore: 93
  },
  {
    id: 'job11',
    title: 'מעצב/ת UX/UI',
    employerId: 'emp1',
    category: 'מוצר ועיצוב',
    location: 'תל אביב',
    workModel: 'remote',
    workDaysOffice: 0,
    employmentType: 'fullTime',
    experienceLevel: 'mid',
    description: 'נחפש מעצב/ת UX/UI יצירתי/ת להצטרף לצוות המוצר. עבודה עם Figma, ניהול design system, מחקר משתמשים.',
    responsibilities: ['עיצוב ממשקים', 'ניהול Design System', 'מחקר משתמשים', 'אב-טיפוס', 'עבודה עם פיתוח'],
    mustHaveRequirements: ['3+ שנות ניסיון ב-UX/UI', 'שליטה מלאה ב-Figma', 'תיק עבודות'],
    niceToHaveRequirements: ['ניסיון עם User Testing', 'ידע ב-HTML/CSS בסיסי'],
    salaryMin: 20000,
    salaryMax: 28000,
    salaryType: 'monthly',
    salaryFlexible: true,
    includesBonus: false,
    includesCar: false,
    includesStudyFund: true,
    includesMeals: true,
    includesOptions: true,
    createdAt: '2026-05-26',
    updatedAt: '2026-05-30',
    lastBoostedAt: null,
    applicantCount: 66,
    viewedApplicantCount: 38,
    interviewCount: 6,
    rejectedCount: 22,
    pendingCount: 38,
    reviewMethod: { humanReview: true, atsReview: false, aiAssisted: false, screeningQuestions: false },
    hiringProcess: [
      { id: 's1', title: 'בחינת תיק עבודות', description: 'סקירת Portfolio', estimatedMinutes: 0, interviewerRole: 'Design Lead' },
      { id: 's2', title: 'ראיון מקצועי', description: 'שיחה על עבודות', estimatedMinutes: 60, interviewerRole: 'Design Lead' },
      { id: 's3', title: 'ראיון משרה', description: 'ראיון עם VP Product', estimatedMinutes: 30, interviewerRole: 'VP Product' }
    ],
    hasHomeAssignment: false,
    averageResponseDays: 4,
    averageProcessDays: 20,
    status: 'active',
    transparencyScore: 86
  },
  {
    id: 'job12',
    title: 'מנהל/ת לקוחות',
    employerId: 'emp2',
    category: 'שיווק ותקשורת',
    location: 'תל אביב',
    workModel: 'hybrid',
    workDaysOffice: 3,
    employmentType: 'fullTime',
    experienceLevel: 'mid',
    description: 'מחפשים מנהל/ת לקוחות לפיתוח ושימור קשרים עם לקוחות עסקיים בחברת הפיננסים שלנו.',
    responsibilities: ['ניהול תיק לקוחות', 'Up-sell ו-Cross-sell', 'בניית קשרים', 'עמידה ביעדים'],
    mustHaveRequirements: ['3+ שנות ניסיון ב-Account Management', 'ניסיון ב-B2B'],
    niceToHaveRequirements: ['ניסיון בפיננסים', 'שליטה באנגלית ברמה גבוהה'],
    salaryMin: 16000,
    salaryMax: 22000,
    salaryType: 'basePlusCommission',
    salaryFlexible: false,
    includesBonus: true,
    bonusPercent: 15,
    includesCar: false,
    includesStudyFund: true,
    includesMeals: true,
    includesOptions: false,
    createdAt: '2026-05-21',
    updatedAt: '2026-05-29',
    lastBoostedAt: '2026-05-26',
    applicantCount: 81,
    viewedApplicantCount: 47,
    interviewCount: 8,
    rejectedCount: 29,
    pendingCount: 44,
    reviewMethod: { humanReview: true, atsReview: true, aiAssisted: false, screeningQuestions: true },
    hiringProcess: [
      { id: 's1', title: 'שיחת HR', description: 'שיחה ראשונית', estimatedMinutes: 20, interviewerRole: 'HR' },
      { id: 's2', title: 'ראיון מכירות', description: 'סימולציית מכירה', estimatedMinutes: 45, interviewerRole: 'Sales Manager' },
      { id: 's3', title: 'ראיון מנהל', description: 'ראיון סיום', estimatedMinutes: 30, interviewerRole: 'VP Customer Success' }
    ],
    hasHomeAssignment: false,
    averageResponseDays: 4,
    averageProcessDays: 18,
    status: 'active',
    transparencyScore: 88
  }
];

// ---- Candidates ----
const CANDIDATES = [
  { id: 'c1', fullName: 'יעל כהן', email: 'yael@example.com', phone: '050-1234567', location: 'תל אביב', currentRole: 'מנהלת שיווק', yearsOfExperience: 6, expectedSalaryMin: 20000, expectedSalaryMax: 28000, availability: 'תוך 30 יום', isConfidential: false, hideCurrentEmployer: false, blockedCompanies: [] },
  { id: 'c2', fullName: 'דוד לוי', email: 'david@example.com', phone: '052-2345678', location: 'ירושלים', currentRole: 'מפתח Full Stack', yearsOfExperience: 4, expectedSalaryMin: 25000, expectedSalaryMax: 35000, availability: 'מיידי', isConfidential: true, hideCurrentEmployer: true, blockedCompanies: ['emp1'] },
  { id: 'c3', fullName: 'מיה ישראל', email: 'maya@example.com', phone: '054-3456789', location: 'רמת גן', currentRole: 'אנליסטית', yearsOfExperience: 3, expectedSalaryMin: 18000, expectedSalaryMax: 24000, availability: 'תוך 14 יום', isConfidential: false, hideCurrentEmployer: false, blockedCompanies: [] },
  { id: 'c4', fullName: 'עמוס שפירא', email: 'amos@example.com', phone: null, location: 'חיפה', currentRole: 'חשב שכר', yearsOfExperience: 7, expectedSalaryMin: 16000, expectedSalaryMax: 20000, availability: 'תוך 60 יום', isConfidential: true, hideCurrentEmployer: true, blockedCompanies: [] },
  { id: 'c5', fullName: 'נועה אברהם', email: 'noa@example.com', phone: '053-4567890', location: 'תל אביב', currentRole: 'מנהלת מוצר', yearsOfExperience: 8, expectedSalaryMin: 32000, expectedSalaryMax: 42000, availability: 'תוך 30 יום', isConfidential: false, hideCurrentEmployer: false, blockedCompanies: [] },
  { id: 'c6', fullName: 'אלי מזרחי', email: 'eli@example.com', phone: '058-5678901', location: 'באר שבע', currentRole: 'מנהל מכירות', yearsOfExperience: 10, expectedSalaryMin: 22000, expectedSalaryMax: 30000, availability: 'תוך 45 יום', isConfidential: false, hideCurrentEmployer: false, blockedCompanies: [] },
  { id: 'c7', fullName: 'שיר גולן', email: 'shir@example.com', phone: '050-6789012', location: 'תל אביב', currentRole: 'מעצבת UX', yearsOfExperience: 5, expectedSalaryMin: 22000, expectedSalaryMax: 30000, availability: 'תוך 30 יום', isConfidential: false, hideCurrentEmployer: false, blockedCompanies: [] },
  { id: 'c8', fullName: 'רון ברק', email: 'ron@example.com', phone: '052-7890123', location: 'נתניה', currentRole: 'מנהל רכש', yearsOfExperience: 5, expectedSalaryMin: 19000, expectedSalaryMax: 25000, availability: 'תוך 30 יום', isConfidential: false, hideCurrentEmployer: false, blockedCompanies: [] }
];

// ---- Applications (for logged-in candidate: c1) ----
const MY_APPLICATIONS = [
  {
    id: 'app1',
    jobId: 'job2',
    candidateId: 'c1',
    appliedAt: '2026-05-21',
    currentStatus: 'recruiterReviewed',
    timeline: [
      { date: '2026-05-21', status: 'submitted', label: 'מועמדות נשלחה', done: true },
      { date: '2026-05-21', status: 'received', label: 'התקבלה במערכת', done: true },
      { date: '2026-05-22', status: 'resumeOpened', label: 'קורות החיים נפתחו', note: 'הצוות צפה בקורות החיים שלך', done: true },
      { date: '2026-05-23', status: 'atsReviewed', label: 'עבר/ה סינון AI', done: true },
      { date: '2026-05-24', status: 'recruiterReviewed', label: 'בבדיקת מגייס/ת', note: 'קורות החיים שלך אצל המגייס/ת', done: true },
      { date: null, status: 'sentToHiringManager', label: 'הועברת למנהל מגייס', done: false },
      { date: null, status: 'interviewInvited', label: 'הזמנה לראיון', done: false }
    ],
    candidateMessage: 'אני מאוד נלהב/ת מהפוזיציה הזו ומאמינ/ה שהניסיון שלי ב-B2B SaaS הוא התאמה מצוינת.',
    rejectionReason: null,
    employerNotes: null
  },
  {
    id: 'app2',
    jobId: 'job5',
    candidateId: 'c1',
    appliedAt: '2026-05-25',
    currentStatus: 'interviewInvited',
    timeline: [
      { date: '2026-05-25', status: 'submitted', label: 'מועמדות נשלחה', done: true },
      { date: '2026-05-25', status: 'received', label: 'התקבלה במערכת', done: true },
      { date: '2026-05-26', status: 'resumeOpened', label: 'קורות החיים נפתחו', done: true },
      { date: '2026-05-27', status: 'recruiterReviewed', label: 'עבר/ה סינון ראשוני', done: true },
      { date: '2026-05-29', status: 'interviewInvited', label: 'הוזמנת לראיון!', note: 'ראיון עם HR ב-02/06 בשעה 14:00', done: true }
    ],
    candidateMessage: null,
    rejectionReason: null,
    employerNotes: null
  },
  {
    id: 'app3',
    jobId: 'job8',
    candidateId: 'c1',
    appliedAt: '2026-05-28',
    currentStatus: 'received',
    timeline: [
      { date: '2026-05-28', status: 'submitted', label: 'מועמדות נשלחה', done: true },
      { date: '2026-05-28', status: 'received', label: 'התקבלה במערכת', done: true },
      { date: null, status: 'resumeOpened', label: 'קורות החיים ייפתחו', done: false },
      { date: null, status: 'atsReviewed', label: 'סינון ATS', done: false }
    ],
    candidateMessage: null,
    rejectionReason: null,
    employerNotes: null
  },
  {
    id: 'app4',
    jobId: 'job11',
    candidateId: 'c1',
    appliedAt: '2026-05-18',
    currentStatus: 'rejected',
    timeline: [
      { date: '2026-05-18', status: 'submitted', label: 'מועמדות נשלחה', done: true },
      { date: '2026-05-18', status: 'received', label: 'התקבלה במערכת', done: true },
      { date: '2026-05-19', status: 'resumeOpened', label: 'קורות החיים נפתחו', done: true },
      { date: '2026-05-22', status: 'rejected', label: 'לא התקדמנו', note: 'סיבה: חסרה מיומנות חובה', done: true }
    ],
    candidateMessage: null,
    rejectionReason: 'missingRequiredSkill',
    employerNotes: null
  },
  {
    id: 'app5',
    jobId: 'job6',
    candidateId: 'c1',
    appliedAt: '2026-05-30',
    currentStatus: 'submitted',
    timeline: [
      { date: '2026-05-30', status: 'submitted', label: 'מועמדות נשלחה', done: true },
      { date: null, status: 'received', label: 'אישור קבלה', done: false }
    ],
    candidateMessage: null,
    rejectionReason: null,
    employerNotes: null
  }
];

// ---- Employer's Applicants (for job1 Kanban) ----
const JOB1_APPLICANTS = [
  { id: 'a1', name: 'רון ברק', role: 'מנהל רכש', exp: '5 שנים', salary: '20,000', status: 'new', appliedAt: '28/05', score: 88, isConfidential: false },
  { id: 'a2', name: 'מועמד/ת דיסקרטי/ת', role: 'רכש ולוגיסטיקה', exp: '4 שנים', salary: '22,000', status: 'new', appliedAt: '29/05', score: 82, isConfidential: true },
  { id: 'a3', name: 'ענת שלום', role: 'מנהלת רכש בכירה', exp: '7 שנים', salary: '24,000', status: 'viewed', appliedAt: '27/05', score: 91, isConfidential: false },
  { id: 'a4', name: 'יוסי כרמי', role: 'קניין', exp: '3 שנים', salary: '18,000', status: 'viewed', appliedAt: '28/05', score: 71, isConfidential: false },
  { id: 'a5', name: 'מירי דהן', role: 'מנהלת שרשרת אספקה', exp: '6 שנים', salary: '21,000', status: 'screening', appliedAt: '26/05', score: 85, isConfidential: false },
  { id: 'a6', name: 'גיל מור', role: 'מנהל רכש', exp: '5 שנים', salary: '20,500', status: 'manager', appliedAt: '25/05', score: 87, isConfidential: false },
  { id: 'a7', name: 'טל אפרת', role: 'מנהלת רכש', exp: '8 שנים', salary: '25,000', status: 'interview1', appliedAt: '24/05', score: 93, isConfidential: false },
  { id: 'a8', name: 'נתן גרוס', role: 'רכש', exp: '3 שנים', salary: '17,000', status: 'rejected', appliedAt: '26/05', score: 62, isConfidential: false },
  { id: 'a9', name: 'שרה פרץ', role: 'מנהלת רכש', exp: '6 שנים', salary: '22,000', status: 'interview1', appliedAt: '25/05', score: 89, isConfidential: false },
  { id: 'a10', name: 'אברהם לוי', role: 'קניין בכיר', exp: '9 שנים', salary: '26,000', status: 'saved', appliedAt: '23/05', score: 79, isConfidential: false }
];

// ---- Employer Dashboard Stats ----
const EMPLOYER_STATS = {
  activeJobs: 3,
  totalApplicants: 211,
  newApplicants: 18,
  unseenApplicants: 7,
  waitingOver7Days: 43,
  upcomingInterviews: 3,
  avgResponseTime: 4.2,
  responseRate: 84,
  performanceScore: 78
};

// ---- Helpers ----
const STATUS_LABELS = {
  submitted: 'נשלחה',
  received: 'התקבלה',
  resumeOpened: 'קורות חיים נפתחו',
  atsReviewed: 'עבר סינון ATS',
  recruiterReviewed: 'בבדיקת מגייס',
  sentToHiringManager: 'הועבר למנהל',
  interviewInvited: 'הוזמן לראיון',
  interviewCompleted: 'ראיון בוצע',
  waitingDecision: 'ממתין להחלטה',
  advanced: 'התקדם',
  offer: 'קיבל הצעה',
  rejected: 'לא התקדם',
  jobClosed: 'משרה נסגרה',
  withdrawn: 'משך מועמדות'
};

const STATUS_COLORS = {
  submitted: 'gray',
  received: 'gray',
  resumeOpened: 'primary',
  atsReviewed: 'primary',
  recruiterReviewed: 'primary',
  sentToHiringManager: 'primary',
  interviewInvited: 'teal',
  interviewCompleted: 'teal',
  waitingDecision: 'warning',
  advanced: 'success',
  offer: 'success',
  rejected: 'error',
  jobClosed: 'gray',
  withdrawn: 'gray'
};

const REJECTION_REASONS = {
  missingExperience: 'חסר ניסיון רלוונטי',
  missingRequiredSkill: 'חסרה מיומנות חובה',
  salaryMismatch: 'ציפיות שכר לא תואמות',
  availabilityMismatch: 'זמינות לא מתאימה',
  locationMismatch: 'מיקום לא מתאים',
  jobClosed: 'המשרה נסגרה',
  roleFrozen: 'התפקיד הוקפא',
  anotherCandidateAdvanced: 'מועמד אחר התקדם',
  notFitForCurrentStage: 'חוסר התאמה לשלב הנוכחי',
  resumeNotClear: 'קורות החיים לא היו מספיק ברורים',
  other: 'אחר'
};

const WORK_MODEL_LABELS = { office: 'משרד מלא', hybrid: 'היברידי', remote: 'מרחוק' };
const EMPLOYMENT_TYPE_LABELS = { fullTime: 'משרה מלאה', partTime: 'משרה חלקית', freelance: 'פרילנס', temporary: 'זמנית' };
const EXPERIENCE_LABELS = { junior: 'ג\'וניור', mid: 'ניסיון בינוני', senior: 'בכיר', manager: 'מנהל' };

function formatSalary(min, max, type) {
  const t = type === 'monthly' ? '/חודש' : type === 'hourly' ? '/שעה' : '';
  if (min && max) return `₪${min.toLocaleString('he-IL')}–${max.toLocaleString('he-IL')}${t}`;
  if (min) return `מ-₪${min.toLocaleString('he-IL')}${t}`;
  return '—';
}

function getEmployer(id) { return EMPLOYERS.find(e => e.id === id); }
function getJob(id) { return JOBS.find(j => j.id === id); }
function daysSince(dateStr) {
  if (!dateStr) return null;
  const d = new Date(dateStr);
  const now = new Date('2026-05-31');
  return Math.floor((now - d) / 86400000);
}

function formatDate(dateStr) {
  if (!dateStr) return '—';
  const [y, m, d] = dateStr.split('-');
  return `${d}/${m}`;
}
